export const PAYLOAD_PROJECTS = "PAYLOAD_PROJECTS";
export const PAYLOAD_PROJECTDETAIL = "PAYLOAD_PROJECTDETAIL";
export const PAYLOAD_PORTAL = "PAYLOAD_PORTAL";

// TODO Create a single action for this
export const PROJECTDETAIL_SET_CLIENT = "PROJECTDETAIL_SET_CLIENT";
export const PROJECTDETAIL_SET_STATUS = "PROJECTDETAIL_SET_STATUS";

// Settings
export const PORTAL_SET_SETTINGS = "PORTAL_SET_SETTINGS";
export const PROJECTS_SET_SETTINGS = "PROJECTS_SET_SETTINGS";
export const PROJECTDETAIL_SET_SETTINGS = "PROJECTDETAIL_SET_SETTINGS";
export const TOGGLE_SIDEBAR_SETTINGS = "TOGGLE_SIDEBAR_SETTINGS";

// Globals
export const PAGE_LOADING = "PAGE_LOADING";
export const FETCHING = "FETCHING";
export const VIDEO_SET = "VIDEO_SET";
export const VIDEO_RENDER = "VIDEO_RENDER"; // Used for tracking window.

export const USER_SET = "USER_SET";
export const ROUTE = "ROUTE";

// Defaults
export const DEFAULTS_SET_LIST = "DEFAULTS_SET_LIST";
