export const PAYLOAD_PROJECTS = 'PAYLOAD_PROJECTS';
export const PAYLOAD_PROJECTDETAIL = 'PAYLOAD_PROJECTDETAIL';
export const PAYLOAD_PORTAL = 'PAYLOAD_PORTAL';

export const PROJECTDETAIL_SET_CLIENT = "PROJECTDETAIL_SET_CLIENT";
export const PROJECTDETAIL_SET_STATUS = "PROJECTDETAIL_SET_STATUS";

export const PAGE_LOADING = 'PAGE_LOADING';
export const FETCHING = 'FETCHING';

export const PAYLOAD_INVOICE = 'PAYLOAD_INVOICE';