export const PAYLOAD_PROJECTS = "PAYLOAD_PROJECTS";
export const PAYLOAD_PROJECTDETAIL = "PAYLOAD_PROJECTDETAIL";
export const PAYLOAD_PORTAL = "PAYLOAD_PORTAL";

export const PROJECTDETAIL_SET_CLIENT = "PROJECTDETAIL_SET_CLIENT";
export const PROJECTDETAIL_SET_STATUS = "PROJECTDETAIL_SET_STATUS";

export const PORTAL_SET_FILTER = "PORTAL_SET_FILTER";
export const PORTAL_SET_SORT = "PORTAL_SET_SORT";

// Globals
export const PAGE_LOADING = "PAGE_LOADING";
export const FETCHING = "FETCHING";
export const INVOICE_SET = "INVOICE_SET";
