pipelines:
  default:
    - step:
        script:  # Modify the commands below to build and test your repository.
          - apt-get update
          - apt-get -y -qq install filezilla
          - chmod +x ./deploy-to-azure.bash
          # - ./deploy-to-azure.bash
