export default ({ admin = false } = {}) => ({
  action: "",
  activeUser: "Active User",
  priorityRender: "Priority",
  statusRender: "Status",
  projectTypeRender: "Type",
  userRender: "Assign User",
  ...(admin ? { videoOptions: "Rendered" } : {}),
  patientName: "Patient Name",
  patientAge: "Age",
  patientSex: "Gender",
  patientBirthDate: "Patient DOB",
  studyType: "Study Type",
  studyDate: "Study Date",
  location: "Facility",
  institutionName: "Location",
  uploadDateTime: "Date Uploaded",
  upload: "Attach Records",
  notes: "Notes"
});
