version: 2
jobs:
  production:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Downloading Artifacts
          command: |
            curl https://circleci.com/api/v1.1/project/github/MultusMedical/application-interface/latest/artifacts?circle-token=$CIRCLE_TOKEN > artifacts.json
            npm i wget-improved
            node ./.circleci/artifacts.js
            rm artifacts.json
      - run:
          name: Install and Build
          command: |
            npm install
            npm run build
      - setup_remote_docker
      - run:
          name: Deploying Production
          command: |
            docker build -t multus/application-server --build-arg MACHINENAME=application-server .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push multus/application-server
  staging:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Downloading Artifacts
          command: |
            curl https://circleci.com/api/v1.1/project/github/MultusMedical/application-interface/latest/artifacts?circle-token=$CIRCLE_TOKEN > artifacts.json
            npm i wget-improved
            node ./.circleci/artifacts.js
            rm artifacts.json
      - run:
          name: Install and Build
          command: |
            npm install
            npm run build
      - setup_remote_docker
      - run:
          name: Deploying Staging
          command: |
            docker build -t multus/application-server:staging --build-arg MACHINENAME=application-server-staging .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push multus/application-server:staging
workflows:
  version: 2
  workflow:
    jobs:
      - staging
      - hold:
          type: approval
          requires:
            - staging
      - production:
          requires:
            - hold
          filters:
            branches:
              only: master
