version: 2
jobs:
  deploy-production:
    docker:
      - image: circleci/node # TODO is there better image to use?
    working_directory: ~/repo
    steps:
      - checkout
      # TODO Add interface submodule
      - setup_remote_docker
      - run:
          name: Deploying Production
          command: |
            docker build -t multus/application-server --build-arg MACHINENAME=application-server .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push multus/application-server
  deploy-staging:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      # TODO Add interface submodule
      - setup_remote_docker
      - run:
          name: Deploying Staging
          command: |
            docker build -t multus/application-server:staging --build-arg MACHINENAME=application-server-staging .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push multus/application-server:staging
workflows:
  version: 2
  build-workflow:
    jobs:
      - deploy-production:
          filters:
            tags:
              only: /.production*/
            branches:
              ignore: /.*/
      - deploy-staging:
          filters:
            branches:
              only: master