version: 2
jobs:
  deploy-production:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Downloading Artifacts
          command: |
            curl https://circleci.com/api/v1.1/project/github/MultusMedical/application-interface/latest/artifacts?circle-token=$CIRCLE_TOKEN > artifacts.json
            npm i wget-improved
            node ./.circleci/artifacts.js
            rm artifacts.json
      - setup_remote_docker
      - run:
          name: Deploying Production
          command: |
            docker build -t multus/application-server --build-arg MACHINENAME=application-server .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push multus/application-server
  deploy-staging:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
        fingerprints:
          - "51:d4:b3:1c:79:54:29:da:09:68:fe:40:05:5d:06:bd"
      - checkout
      - run:
          name: Downloading Artifacts
          command: |
            curl https://circleci.com/api/v1.1/project/github/MultusMedical/application-interface/latest/artifacts?circle-token=$CIRCLE_TOKEN > artifacts.json
            npm i wget-improved
            node ./.circleci/artifacts.js
            rm artifacts.json
      - setup_remote_docker
      - run:
          name: Deploying Staging
          command: |
            # cp ${HOME}/.ssh/id_rsa_circleci_remote_docker_engine id_rsa
            ls ${HOME}/.ssh
            docker build -t multus/application-server:staging --build-arg MACHINENAME=application-server-staging .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push multus/application-server:staging
workflows:
  version: 2
  build-workflow:
    jobs:
      - deploy-production:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy-staging:
          filters:
            branches:
              only: master
